---
# main playbook: orochi.yml
- name: Deploy orochi Security Stack
  hosts: orochi_servers
  become: yes
  vars_prompt:
    - name: "elastic_password"
      prompt: "Enter password for Elastic services"
      private: yes
      confirm: yes
    
    - name: "velox_user"
      prompt: "Enter Velociraptor username"
      default: "admin"
      private: no
    
    - name: "selected_interface"
      prompt: "Enter network interface for monitoring (or press Enter to auto-detect)"
      default: ""
      private: no

  vars:
    stack_version: "9.2.2"
    cluster_name: "OROCHI"
    license_type: "basic"
    mem_limit: "8g"
    es_port: 9200
    kibana_port: 5601
    fleet_port: 8220
    suricata_port: 8000
    arkime_port: 8005
    mattermost_port: 8065
    velociraptor_port: 8889
    thehive_port: 9000
    cyberchef_port: 7000
    velox_role: "administrator"
    
  tasks:
    - name: Include variable initialization
      import_tasks: tasks/00_init_vars.yml
      tags: always

    - name: Install prerequisites
      import_tasks: tasks/01_prerequisites.yml
      tags: [prerequisites, always]

    - name: Configure environment
      import_tasks: tasks/02_configure_env.yml
      tags: [config, always]

    - name: Deploy ELK Stack
      import_tasks: tasks/03_elk.yml
      tags: [elk, elastic]
      when: "'elk' in deploy_components or 'all' in deploy_components"

    - name: Deploy Fleet Server
      import_tasks: tasks/04_fleet.yml
      tags: [fleet]
      when: "'fleet' in deploy_components or 'all' in deploy_components"

    - name: Deploy Arkime
      import_tasks: tasks/05_arkime.yml
      tags: [arkime]
      when: "'arkime' in deploy_components or 'all' in deploy_components"

    - name: Deploy TheHive
      import_tasks: tasks/06_hive.yml
      tags: [hive]
      when: "'hive' in deploy_components or 'all' in deploy_components"

    - name: Deploy Velociraptor
      import_tasks: tasks/07_velociraptor.yml
      tags: [velociraptor]
      when: "'velociraptor' in deploy_components or 'all' in deploy_components"

    - name: Deploy Mattermost
      import_tasks: tasks/08_mattermost.yml
      tags: [mattermost]
      when: "'mattermost' in deploy_components or 'all' in deploy_components"

    - name: Deploy Suricata
      import_tasks: tasks/09_suricata.yml
      tags: [suricata]
      when: "'suricata' in deploy_components or 'all' in deploy_components"

    - name: Deploy CyberChef
      import_tasks: tasks/10_cyberchef.yml
      tags: [cyberchef]
      when: "'cyberchef' in deploy_components or 'all' in deploy_components"

    - name: Deploy Zeek
      import_tasks: tasks/11_zeek.yml
      tags: [zeek]
      when: "'zeek' in deploy_components or 'all' in deploy_components"

    - name: Deploy RITA
      import_tasks: tasks/12_rita.yml
      tags: [rita]
      when: "'rita' in deploy_components or 'all' in deploy_components"

    - name: Build Dashboard Website
      import_tasks: tasks/13_website.yml
      tags: [website]
      when: "'website' in deploy_components or 'all' in deploy_components"

    - name: Display access information
      import_tasks: tasks/14_display_info.yml
      tags: always