#!/usr/bin/env ansible-playbook
---
# setup.yml - Bootstrap playbook to prepare the control node and target hosts
- name: Bootstrap Orochi Deployment Environment
  hosts: orochi_servers
  gather_facts: yes
  become: yes

  tasks:
    - name: Display setup banner
      debug:
        msg:
          - "=========================================="
          - "  Orochi Ansible Setup"
          - "=========================================="
          - "This playbook will prepare your environment"
          - "for deploying the Orochi security stack."

    - name: Check if running on supported OS
      assert:
        that:
          - ansible_os_family == "Debian"
        fail_msg: "This playbook requires Debian/Ubuntu"
        success_msg: "OS check passed: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Install Ansible if not present
      become: yes
      apt:
        name: ansible
        state: present
        update_cache: yes
      when: ansible_version is not defined

    - name: Install required system packages
      become: yes
      apt:
        name:
          - python3-pip
          - git
          - software-properties-common
        state: present

    - name: Install Python Docker library
      pip:
        name:
          - docker
          - docker-compose
        state: present
        extra_args: --user

    - name: Check if Ansible collections are installed
      shell: ansible-galaxy collection list | grep -E "community.docker|community.general"
      register: collections_check
      changed_when: false
      failed_when: false

    - name: Install Ansible collections from requirements.yml
      shell: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      when: collections_check.rc != 0

    - name: Verify inventory file exists
      stat:
        path: "{{ playbook_dir }}/inventory/hosts.ini"
      register: inventory_file

    - name: Check if inventory is configured
      assert:
        that:
          - inventory_file.stat.exists
        fail_msg: "Inventory file not found at inventory/hosts.ini"
        success_msg: "Inventory file found"

    - name: Verify group_vars exists
      stat:
        path: "{{ playbook_dir }}/group_vars/orochi_servers.yml"
      register: groupvars_file

    - name: Check if group_vars is configured
      assert:
        that:
          - groupvars_file.stat.exists
        fail_msg: "Group vars not found at group_vars/orochi_servers.yml"
        success_msg: "Group vars file found"

    - name: Verify docker-compose.yml exists
      stat:
        path: "{{ playbook_dir }}/files/docker-compose.yml"
      register: compose_file

    - name: Check critical docker-compose.yml file
      assert:
        that:
          - compose_file.stat.exists
        fail_msg: "CRITICAL: docker-compose.yml not found at files/docker-compose.yml"
        success_msg: "Docker Compose file found"

    - name: Count task files
      find:
        paths: "{{ playbook_dir }}/tasks"
        patterns: "*.yml"
      register: task_files

    - name: Verify all task files exist
      assert:
        that:
          - task_files.matched >= 15
        fail_msg: "Missing task files. Expected at least 15, found {{ task_files.matched }}"
        success_msg: "All {{ task_files.matched }} task files found"

    - name: Count template files
      find:
        paths: "{{ playbook_dir }}/templates"
        patterns: "*.j2"
      register: template_files

    - name: Verify all template files exist
      assert:
        that:
          - template_files.matched >= 3
        fail_msg: "Missing template files. Expected at least 3, found {{ template_files.matched }}"
        success_msg: "All {{ template_files.matched }} template files found"

    - name: Test connection to target hosts
      delegate_to: "{{ item }}"
      ping:
      loop: "{{ groups['orochi_servers'] }}"
      when: groups['orochi_servers'] is defined

    - name: Display setup summary
      debug:
        msg:
          - "=========================================="
          - "  Setup Complete!"
          - "=========================================="
          - ""
          - "Environment verified:"
          - "  ✓ Ansible installed"
          - "  ✓ Python libraries installed"
          - "  ✓ Ansible collections installed"
          - "  ✓ Inventory file exists"
          - "  ✓ Group vars configured"
          - "  ✓ Docker Compose file present"
          - "  ✓ {{ task_files.matched }} task files found"
          - "  ✓ {{ template_files.matched }} template files found"
          - "  ✓ Target hosts reachable"
          - ""
          - "Ready to deploy!"
          - "Run: ansible-playbook orochi.yml"
          - "=========================================="

- name: Prepare Target Hosts (if remote)
  hosts: orochi_servers
  gather_facts: yes
  become: yes

  tasks:
    - name: Display target host info
      debug:
        msg: "Preparing host: {{ inventory_hostname }} ({{ ansible_host | default('localhost') }})"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_connection != 'local'

    - name: Check available disk space
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space
      changed_when: false

    - name: Display disk space
      debug:
        msg: "Available disk space on {{ inventory_hostname }}: {{ disk_space.stdout }}"

    - name: Check available memory
      shell: free -h | awk 'NR==2 {print $7}'
      register: memory_available
      changed_when: false

    - name: Display available memory
      debug:
        msg: "Available memory on {{ inventory_hostname }}: {{ memory_available.stdout }}"

    - name: Verify minimum disk space (50GB)
      shell: df / | awk 'NR==2 {print $4}'
      register: disk_kb
      changed_when: false
      failed_when: disk_kb.stdout | int < 52428800  # 50GB in KB

    - name: Display target readiness
      debug:
        msg:
          - "Host {{ inventory_hostname }} is ready for deployment"
          - "Disk space: {{ disk_space.stdout }}"
          - "Memory available: {{ memory_available.stdout }}"