---
- name: Check and Install Docker
  hosts: target_servers
  become: true  # Need sudo for installation
  gather_facts: true

  tasks:
    # Check if Docker is installed
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true
      changed_when: false

    - name: Display current Docker status
      ansible.builtin.debug:
        msg: "{{ 'Docker already installed: ' + docker_installed.stdout if docker_installed.rc == 0 else 'Docker not found - will install' }}"

    # ============================================
    # Install Docker on Debian/Ubuntu
    # ============================================
    - name: Install Docker on Debian/Ubuntu
      when: 
        - docker_installed.rc != 0
        - ansible_os_family == "Debian"
      block:
        - name: Install required packages
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present
            update_cache: true

        - name: Create keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add Docker GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
            state: present
            filename: docker

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest
            update_cache: true

    # ============================================
    # Install Docker on RHEL/CentOS/Fedora
    # ============================================
    - name: Install Docker on RHEL/CentOS/Fedora
      when: 
        - docker_installed.rc != 0
        - ansible_os_family == "RedHat"
      block:
        - name: Install required packages
          ansible.builtin.yum:
            name:
              - yum-utils
            state: present

        - name: Add Docker repository
          ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE Stable
            baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
            gpgcheck: true
            gpgkey: https://download.docker.com/linux/centos/gpg
            enabled: true

        - name: Install Docker packages
          ansible.builtin.yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest

    # ============================================
    # Post-installation tasks
    # ============================================
    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      when: docker_installed.rc != 0

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      when: docker_installed.rc != 0

    # ============================================
    # Verify installation
    # ============================================
    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_final_version
      changed_when: false

    - name: Display final Docker status
      ansible.builtin.debug:
        msg: "Docker is ready: {{ docker_final_version.stdout }}"

    - name: Get Docker info
      ansible.builtin.command: "docker info --format '{% raw %}Server Version: {{.ServerVersion}}, Storage Driver: {{.Driver}}{% endraw %}'"
      register: docker_info
      changed_when: false

    - name: Display Docker info
      ansible.builtin.debug:
        msg: "{{ docker_info.stdout }}"