#!/usr/bin/env ansible-playbook
---
- name: Reset Orochi Installation
  hosts: orochi_servers
  become: true
  gather_facts: false

  tasks:
    - name: Confirm reset
      pause:
        prompt: "This will remove all Orochi containers and data (except .env). Continue? (yes/no)"
      register: confirm_reset

    - name: Abort if not confirmed
      fail:
        msg: "Reset aborted by user"
      when: confirm_reset.user_input | lower != 'yes'

    - name: Display reset starting
      debug:
        msg: "Starting Orochi reset process..."

    # ============================================
    # Stop and Remove Containers
    # ============================================
    - name: Stop Orochi containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - fleet-server
        - kibana
        - elasticsearch
      ignore_errors: yes

    - name: Display containers removed
      debug:
        msg: "All Orochi containers stopped and removed"

    # ============================================
    # Remove Data Directories
    # ============================================
    - name: Remove Orochi data directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/orochi/certs
        - /opt/orochi/esdata
        - /opt/orochi/kibanadata
        - /opt/orochi/fleetserverdata

    - name: Display data directories removed
      debug:
        msg: "All Orochi data directories removed"

    # ============================================
    # Summary
    # ============================================
    - name: Display reset complete
      debug:
        msg:
          - "=========================================="
          - "     Reset Complete!"
          - "=========================================="
          - ""
          - "Removed:"
          - "  - All Orochi containers"
          - "  - All data directories"
          - ""
          - "Preserved:"
          - "  - .env file"
          - ""
          - "To reinstall, run: ./fuse.yml"
          - "=========================================="