---
all:
  children:
    orochi_servers:
      hosts:
        orochi-node:
          ansible_host: 100.106.108.5
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_user: robbo