#!/usr/bin/ansible-playbook
---
- name: Reset Project OROCHI - Clean ELK Stack deployment
  hosts: elk_servers
  become: yes
  vars:
    data_path: /opt/OROCHI/
    elastic_network: orochi-network
    
  tasks:
    - name: Display reset warning
      debug:
        msg:
          - "WARNING: This will destroy all Project OROCHI data!"
          - "Stopping containers, removing networks, and deleting data..."
    
    # === PROPER DOCKER CLEANUP ===
    - name: Complete Docker cleanup
      block:
        - name: Stop all running Docker containers
          shell: docker stop $(docker ps -aq) 2>/dev/null || true
          ignore_errors: yes
        
        - name: Remove all Docker containers
          shell: docker rm $(docker ps -aq) 2>/dev/null || true
          ignore_errors: yes
        
        - name: Remove Project OROCHI Docker network
          docker_network:
            name: "{{ elastic_network }}"
            state: absent
          ignore_errors: yes
        
        - name: Remove all unused Docker networks
          shell: docker network rm $(docker network ls -q | grep -v "bridge\|host\|none") 2>/dev/null || true
          ignore_errors: yes
        
        - name: Remove all Docker volumes
          shell: docker volume rm $(docker volume ls -q) 2>/dev/null || true
          ignore_errors: yes
        
        - name: Clean up unused Docker resources
          shell: docker system prune -af
          ignore_errors: yes
        
        - name: Stop Docker services completely
          systemd:
            name: "{{ item }}"
            state: stopped
          loop:
            - docker.service
            - docker.socket
            - containerd.service
          ignore_errors: yes
        
        # COMPLETE DOCKER REMOVAL for true vanilla state
        - name: Remove Docker packages completely
          apt:
            name:
              - docker.io
              - docker-compose
              - containerd
              - runc
            state: absent
            purge: yes
          ignore_errors: yes
        
        - name: Remove Docker directories and config
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /var/lib/docker
            - /var/lib/containerd
            - /etc/docker
            - /var/run/docker.sock
          ignore_errors: yes
        
        - name: Remove any Docker systemd override files
          shell: |
            rm -rf /etc/systemd/system/docker.service.d/
            rm -rf /etc/systemd/system/containerd.service.d/
          ignore_errors: yes
        
        - name: Reload systemd after Docker removal
          systemd:
            daemon_reload: yes

      rescue:
        - name: Force Docker cleanup if normal cleanup fails
          shell: |
            # Kill any remaining Docker processes
            pkill -f docker || true
            pkill -f containerd || true
            
            # Force remove packages
            apt remove --purge -y docker.io docker-compose containerd runc || true
            
            # Force remove directories
            rm -rf /var/lib/docker /var/lib/containerd /etc/docker
            
            # Clean systemd
            systemctl daemon-reload
          ignore_errors: yes

    # === PROJECT DATA CLEANUP ===
    - name: Remove Project OROCHI data directory
      file:
        path: "{{ data_path }}"
        state: absent
    
    - name: Remove ELK Docker compose directory
      file:
        path: /opt/elk-docker
        state: absent
    
    # === SYSTEM CLEANUP ===
    - name: Clean package cache
      apt:
        autoclean: yes
        autoremove: yes
    
    - name: Display reset completion
      debug:
        msg:
          - "Project OROCHI reset complete!"
          - "All containers stopped and removed"
          - "All data in {{ data_path }} deleted"
          - "Docker completely removed for vanilla state"
          - "System ready for fresh ELK deployment"