#!/usr/bin/env ansible-playbook
---
# ==============================================
# OROCHI SECURITY STACK - INTERACTIVE DEPLOYER
# ==============================================

- name: Orochi Security Stack Deployer
  hosts: orochi_servers
  become: true
  gather_facts: true
  
  vars_files:
    - vars/secrets.yml

  vars:
    menu_options:
      "1": "Deploy Complete Stack (All Services)"
      "2": "Deploy Elastic Stack (Elasticsearch + Kibana + Fleet)"
      "3": "Deploy TheHive 4 (Incident Response)"
      "4": "Deploy Velociraptor (DFIR & Endpoint Visibility)"
      "5": "Deploy Zeek (Network Analysis)"
      "6": "Deploy Suricata (Network IDS)"
      "7": "Deploy Arkime (Full Packet Capture)"
      "8": "Deploy CyberChef (Data Analysis)"
      "9": "Deploy Mattermost (Team Communication)"
      "10": "Deploy RITA (Network Traffic Analysis)"
      "11": "Deploy Tool Portal (Dashboard)"
      "12": "Show Current Status"
      "13": "Teardown (Remove All)"
      "0": "Exit"

  pre_tasks:
    - name: Display Orochi Banner
      ansible.builtin.debug:
        msg: |
          
          ╔═══════════════════════════════════════════════════════════════╗
          ║                                                               ║
          ║     ██████  ██████   ██████   ██████ ██   ██ ██               ║
          ║    ██    ██ ██   ██ ██    ██ ██      ██   ██ ██               ║
          ║    ██    ██ ██████  ██    ██ ██      ███████ ██               ║
          ║    ██    ██ ██   ██ ██    ██ ██      ██   ██ ██               ║
          ║     ██████  ██   ██  ██████   ██████ ██   ██ ██               ║
          ║                                                               ║
          ║              SECURITY STACK DEPLOYER v1.0                     ║
          ║         Based on Project Tiamat by csquirrel84                ║
          ║                                                               ║
          ╚═══════════════════════════════════════════════════════════════╝
          
          Target Host: {{ inventory_hostname }}
          Server IP: {{ ansible_default_ipv4.address | default('N/A') }}
          
      tags: always

    - name: Display Menu
      ansible.builtin.debug:
        msg: |
          
          ┌─────────────────────────────────────────┐
          │           DEPLOYMENT OPTIONS            │
          ├─────────────────────────────────────────┤
          │  1. Deploy Complete Stack               │
          │  2. Deploy Elastic Stack                │
          │  3. Deploy TheHive 4                    │
          │  4. Deploy Velociraptor                 │
          │  5. Deploy Zeek                         │
          │  6. Deploy Suricata                     │
          │  7. Deploy Arkime                       │
          │  8. Deploy CyberChef                    │
          │  9. Deploy Mattermost                   │
          │ 10. Deploy RITA                         │
          │ 11. Deploy Tool Portal                  │
          │ 12. Show Status                         │
          │ 13. Teardown All                        │
          │  0. Exit                                │
          └─────────────────────────────────────────┘
          
      when: menu_choice is not defined
      tags: always

    - name: Prompt for selection
      ansible.builtin.pause:
        prompt: "Enter your choice [1-13, 0 to exit]"
      register: user_input
      when: menu_choice is not defined
      tags: always

    - name: Set menu choice
      ansible.builtin.set_fact:
        menu_choice: "{{ user_input.user_input | default(menu_choice) }}"
      tags: always

  tasks:
    # Exit
    - name: Exit if selected
      ansible.builtin.meta: end_play
      when: menu_choice == "0"

    # Option 1: Deploy All
    - name: Deploy Complete Stack
      when: menu_choice == "1"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: certificates
        - ansible.builtin.include_role:
            name: elasticsearch
        - ansible.builtin.include_role:
            name: kibana
        - ansible.builtin.include_role:
            name: fleet
        - ansible.builtin.include_role:
            name: thehive
        - ansible.builtin.include_role:
            name: velociraptor
        - ansible.builtin.include_role:
            name: suricata
        - ansible.builtin.include_role:
            name: zeek
        - ansible.builtin.include_role:
            name: arkime
        - ansible.builtin.include_role:
            name: cyberchef
        - ansible.builtin.include_role:
            name: mattermost
        - ansible.builtin.include_role:
            name: rita
        - ansible.builtin.include_role:
            name: nginx_proxy

    # Option 2: Elastic Stack
    - name: Deploy Elastic Stack
      when: menu_choice == "2"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: certificates
        - ansible.builtin.include_role:
            name: elasticsearch
        - ansible.builtin.include_role:
            name: kibana
        - ansible.builtin.include_role:
            name: fleet

    # Option 3: TheHive
    - name: Deploy TheHive
      when: menu_choice == "3"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: thehive

    # Option 4: Velociraptor
    - name: Deploy Velociraptor
      when: menu_choice == "4"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: velociraptor

    # Option 5: Zeek
    - name: Deploy Zeek
      when: menu_choice == "5"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: zeek

    # Option 6: Suricata
    - name: Deploy Suricata
      when: menu_choice == "6"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: suricata

    # Option 7: Arkime
    - name: Deploy Arkime
      when: menu_choice == "7"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: certificates
        - ansible.builtin.include_role:
            name: elasticsearch
        - ansible.builtin.include_role:
            name: arkime

    # Option 8: CyberChef
    - name: Deploy CyberChef
      when: menu_choice == "8"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: cyberchef

    # Option 9: Mattermost
    - name: Deploy Mattermost
      when: menu_choice == "9"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: mattermost

    # Option 10: RITA
    - name: Deploy RITA
      when: menu_choice == "10"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: rita

    # Option 11: Tool Portal
    - name: Deploy Tool Portal
      when: menu_choice == "11"
      block:
        - ansible.builtin.include_role:
            name: common
        - ansible.builtin.include_role:
            name: environment
        - ansible.builtin.include_role:
            name: certificates
        - ansible.builtin.include_role:
            name: nginx_proxy

    # Option 12: Status
    - name: Show Status
      when: menu_choice == "12"
      block:
        - name: Get running containers
          ansible.builtin.command: docker ps --format "table {% raw %}{{.Names}}\t{{.Status}}\t{{.Ports}}{% endraw %}"
          register: container_status
          changed_when: false

        - name: Display container status
          ansible.builtin.debug:
            msg: "{{ container_status.stdout_lines }}"

    # Option 13: Teardown
    - name: Teardown All
      when: menu_choice == "13"
      block:
        - name: Confirm teardown
          ansible.builtin.pause:
            prompt: "WARNING: This will remove all Orochi containers and data. Type 'YES' to confirm"
          register: confirm_teardown

        - name: Stop Arkime services (bare metal)
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop:
            - arkimecapture
            - arkimeviewer
          ignore_errors: true
          when: confirm_teardown.user_input == "YES"

        - name: Stop all Orochi containers
          community.docker.docker_container:
            name: "{{ item }}"
            state: absent
          loop:
            - tool-portal
            - rita
            - mongodb-rita
            - mattermost
            - postgres-mattermost
            - cyberchef
            - suricata
            - velociraptor
            - thehive
            - cassandra
            - elasticsearch-hive
            - fleet-server
            - kibana
            - elasticsearch
          ignore_errors: true
          when: confirm_teardown.user_input == "YES"

        - name: Remove Docker network
          community.docker.docker_network:
            name: "{{ orochi_network_name | default('orochi-network') }}"
            state: absent
          ignore_errors: true
          when: confirm_teardown.user_input == "YES"

  post_tasks:
    - name: Display Access Information
      ansible.builtin.debug:
        msg: |
          
          ╔═══════════════════════════════════════════════════════════════╗
          ║                    DEPLOYMENT COMPLETE                        ║
          ╠═══════════════════════════════════════════════════════════════╣
          ║  Configuration saved to ./orochi/.env (control node)          ║
          ║  Credentials stored in vars/secrets.yml (vault encrypted)     ║
          ║                                                               ║
          ║  Common Services:                                             ║
          ║  • Elasticsearch: https://<IP>:9200                           ║
          ║  • Kibana:        https://<IP>:5601                           ║
          ║  • Fleet Server:  https://<IP>:8220                           ║
          ║  • TheHive:       http://<IP>:9000                            ║
          ║  • Velociraptor:  https://<IP>:8889                           ║
          ╚═══════════════════════════════════════════════════════════════╝
          
      when: menu_choice not in ["0", "11", "12"]
      tags: always